# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChatApp_Firebase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
pod 'Firebase/Firestore'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'MessageKit'
pod 'SDWebImage'


end
